spring:
  datasource:
    username: ${ROOT:root}
    password: ${ROOT_PASSWORD:1234}
    url: jdbc:mysql://${TICKET_MYSQL_HOST:localhost}:4306/ticket_trove?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      port: 6379
      host: 127.0.0.1
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    root: info

server:
  port: ${SERVER_PORT:8001}


